export enum ActionEnum {
  ADD_AUTHOR = 'add_author',
  ADD_MEMBER = 'add_member',
  CHANGE_STATUS = 'change_status',
  CREATE = 'create',
  DELETE = 'delete',
  NEW_ASSIGNMENT = 'new_assignment',
  NEW_MENTION = 'new_mention',
  NEW_VERSION = 'new_version',
  PASSWORD_CHANGE = 'password_change',
  PIN = 'pin',
  PIN_GLOBAL = 'pin_global',
  REGISTER = 'register',
  REPLY = 'reply',
  REMOVE_ASSIGNMENT = 'remove_assignment',
  REMOVE_MEMBER = 'remove_member',
  STAR = 'star',
  UNPIN = 'unpin',
  UNPIN_GLOBAL = 'unpin_global',
  UNSTAR = 'unstar',
  UPDATE = 'update',
  UPDATE_REPLY = 'update_reply',
  UPDATE_MEMBER_ROLE = 'update_member_role',
  VERIFICATION_EMAIL = 'verification_email',
}
